image:
  file: .gitpod.dockerfile

tasks:
  - name: mattermost-ai-server
    init: pip install -r requirements.txt; cp config.example.toml config.toml; sed -i 's/localhost/0.0.0.0/' config.toml; sed -i 's/models.fake_gpt.FakeGPT/models.mpt7bchat.Mpt7bChat/' config.toml
    command: python run.py

ports:
  - name: mattermost-ai-server
    port: 8090
    onOpen: ignore
